# Generated by Django 4.1.5 on 2023-01-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Github',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceTitle', models.CharField(max_length=100)),
                ('resourceDescriptions', models.TextField()),
                ('rcLinks', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceTitle', models.CharField(max_length=100)),
                ('resourceDescriptions', models.TextField()),
                ('rcLinks', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceTitle', models.CharField(max_length=100)),
                ('resourceDescriptions', models.TextField()),
                ('rcLinks', models.URLField()),
            ],
        ),
    ]
