# Generated by Django 4.1.5 on 2023-01-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_title', models.CharField(max_length=100)),
                ('classLink', models.URLField()),
                ('aboutClass', models.TextField()),
                ('github', models.ManyToManyField(to='lms.github')),
                ('website', models.ManyToManyField(to='lms.website')),
                ('youtube', models.ManyToManyField(to='lms.youtube')),
            ],
        ),
    ]
