# Generated by Django 4.1.5 on 2023-01-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfCourse', models.CharField(max_length=100)),
                ('uploadTime', models.DateTimeField()),
                ('descriptions', models.TextField()),
                ('classes', models.ManyToManyField(to='lms.classes')),
            ],
        ),
    ]
